### ISSUE TITLE
credential issuance fails

### ISSUE THREAD

**Issue by pimvullers** [credentials/irma_web_service#2]
Issuance of credentials fails, all card communication works fine, but when verifying the card response at the server the issuer does not accept the proof. (the computed c values do not match)

**Comment by pimvullers** [comment]
The actual exception that occurs:

<pre>
Nov 29, 2012 4:11:51 PM org.restlet.resource.UniformResource doCatch
WARNING: Exception or error caught in resource
java.lang.NullPointerException
    at service.IdemixSmartcard.round3Commands(Unknown Source)
    at org.irmacard.credentials.idemix.IdemixCredentials.requestIssueRound3Commands(IdemixCredentials.java:330)
    at org.irmacard.credentials.idemix.IdemixCredentials.requestIssueRound3Commands(IdemixCredentials.java:323)
    at org.irmacard.web.restapi.resources.IssueStudentCredResource.processIssuance(IssueStudentCredResource.java:222)
    at org.irmacard.web.restapi.resources.IssueStudentCredResource.handlePost(IssueStudentCredResource.java:78)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:449)
    at org.restlet.resource.ServerResource.post(ServerResource.java:1114)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:533)
    at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:590)
    at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:302)
    at org.restlet.resource.ServerResource.handle(ServerResource.java:849)
    at org.restlet.resource.Finder.handle(Finder.java:513)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:500)
    at org.restlet.routing.Router.handle(Router.java:740)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.engine.ChainHelper.handle(ChainHelper.java:114)
    at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)
    at org.restlet.Application.handle(Application.java:391)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:500)
    at org.restlet.routing.Router.handle(Router.java:740)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.routing.Router.doHandle(Router.java:500)
    at org.restlet.routing.Router.handle(Router.java:740)
    at org.restlet.routing.Filter.doHandle(Filter.java:159)
    at org.restlet.routing.Filter.handle(Filter.java:206)
    at org.restlet.engine.ChainHelper.handle(ChainHelper.java:114)
    at org.restlet.Component.handle(Component.java:391)
    at org.restlet.Server.handle(Server.java:491)
    at org.restlet.engine.ServerHelper.handle(ServerHelper.java:74)
    at org.restlet.engine.http.HttpServerHelper.handle(HttpServerHelper.java:153)
    at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1031)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
</pre>

This is caused by a failed proof from the card which makes the issuer return a null value.

**Comment by wouterl** [comment]
I can reproduce this bug now. Additionally, the idemix-library reports that:

Nov 30, 2012 10:41:52 AM com.ibm.zurich.idmx.issuance.Issuer round2
SEVERE: mismatching c, cHat (56800310143623519506894360180890863256772264430, 948364726206023218353190184732489985526337995068)

**Comment by wouterl** [comment]
At least on my machine, this bug can be circumvented as follows:
1. Start verification
2. After verification power-cycle the card (proper card-binding should prevent this from every succeeding, but for now this is rather useful).
3. The javascript will automatically reselect the applet
4. Proceed with issuing as normal.

This seems to work in the sense that after another power-cycle the credential actually verifies. I could repeat this once without the webinterface, but really only once,:
1. Run a verification, say verifyRootCredentialAll
2. Do _not_ power cycle the card
3. Run an issuance, say issueAgeCredential afterwards.

The result was the same severe error as in my previous post.

**Comment by wouterl** [comment]
Fixed by credentials/idemix-multos@79c92d6fdf0950067845251de4216befaf69ffc5.
